### ISSUE TITLE
BUG: Can't create a Feature

### ISSUE THREAD

**Issue by adrian-goe** [angular-architects/nx-ddd-plugin#100]
I have created a domain with `ng g @angular-architects/ddd:domain demo` without creating an extra app.
The Domain was created in the lib directory.

Now I want to add a feature with  `ng g @angular-architects/ddd:feature demo --domain demo`

### Expected
A new lib with the feature in the dir `libs/demo`

### Current behavior
There is an error in the Console
`Specified app demo does not exist: apps/demo/src/app/app.module.ts expected!`

I'm not sure why it's trying to find an app.

**Comment by adrian-goe** [comment]
I use 
```text
"@angular-architects/ddd": "2.0.0",
"@angular/common": "~13.1.0",
"@nrwl/cli": "13.3.12",
```

**Comment by manfredsteyer** [comment]
Can you pls try to add the --noApp switch when creating a feature?

**Comment by adrian-goe** [comment]
it returns 
```bash
$ ng g @angular-architects/ddd:feature demo --domain demo --noApp
(0 , utils_1.insertNgModuleProperty) is not a function
```

**Comment by AsimNet** [comment]
`yarn nx generate @angular-architects/ddd:feature --name=audio-player --app=myApp --domain=player --entity=AudioPlayer --ngrx --no-interactive`

same here

**Comment by mohammedmatar** [comment]
Nice to see you all, _i am facing the exact issue_ and i was able to generate the feature library after
updating my nx monorepo to the latest version.
Hope this works for you !

**Comment by adrian-goe** [comment]
thx @mohammedmatar this worked also for me. I close it for now, feel free to reopen this.
