### ISSUE TITLE
Specified app flight-app does not exist: apps/flight-app/src/app/app.module.ts expected! in v14

### ISSUE THREAD

**Issue by jon9090** [angular-architects/nx-ddd-plugin#108]
@manfredsteyer  I got an error when trying to create feature in v14:

> Specified app flight-app does not exist: apps/flight-app/src/app/app.module.ts expected!

Because I using imports inside the component I don't have `app.module.ts` anymore.

**Comment by manfredsteyer** [comment]
The next version (2.1, just landed) supports standalone components with a ``--standalone`` switch.
