### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by vladimirdrayling** [angular-architects/nx-ddd-plugin#11]
### Steps to reproduce:

* `npx create-nx-workspace@latest workspace-name --preset=empty --cli=angular --style=scss --nx-cloud=false`
* Tried with `ng add @angular-architects/ddd` and `nx add @angular-architects/ddd`

### Environment

* Node v12.17.0
* yarn 1.22.4
* nx 9.5.1

**Comment by manfredsteyer** [comment]
Thanks for this info. Hm, do you have a ``tslint.json`` in your project's root? This is the only file which is modified by the ng add schematic.

**Comment by BeaveArony** [comment]
NX allows to generate an application with eslint as linter instead of tslint (which is the default). Choosing eslint will create the `.eslintrc` file. 
The ng add command should probably add the rules to this part as well:
```json
{
  "rules": {
    "@typescript-eslint/explicit-member-accessibility": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/no-parameter-properties": "off",
    "@nrwl/nx/enforce-module-boundaries": [
      "error",
      {
        "enforceBuildableLibDependency": true,
        "allow": [],
        "depConstraints": [
          { "sourceTag": "*", "onlyDependOnLibsWithTags": ["*"] }
        ]
      }
    ]
  }
}
```

**Comment by peterbsmith2** [comment]
confirmed on new repositories that this is related to eslint.
