### ISSUE TITLE
ddd generate doesnt work anymore on the latest @nrwl/workspace versions.

### ISSUE THREAD

**Issue by mawebdev** [angular-architects/nx-ddd-plugin#123]
<img width="1099" alt="Bildschirm­foto 2023-04-11 um 12 04 48" src="https://user-images.githubusercontent.com/17885780/231128351-6b8f3381-2a5c-49d5-8b5c-0212873b1940.png">

ast-utils was moved from @nrwl/workspace to @nrwl/js (Reference: https://github.com/nrwl/nx/pull/15540)

Solution:
node_modules/@angular-architects/ddd/src/generators/utils/addToNgModule.js:5
`const ast_utils_1 = require("@nrwl/js/src/utils/typescript/ast-utils");`

**Comment by orlandoji** [comment]
hi there i have same error 
Cannot find module `@nrwl/workspace/src/utilities/ast-utils`

`"@nrwl/workspace": "^15.9.2"`

**Comment by ido-lempert** [comment]
Changing ```import { insertImport } from @nrwl/workspace/src/utilities/ast-utils``` to ```import { insertImport } from 
 @nrwl/js``` works for me.

**Comment by innoveltec** [comment]
I am having the same issue "@nx/workspace": "16.0.1", where did you change this import?

**Comment by elite-benni** [comment]
in node_modules index.ts you can change ast utils import to **const ast_utils_1 = require("@nx/workspace/src/utils/ast-utils");**

As there are some other problems with nx changing some paths, to be sure maybe it is better to wait for manfreds update. ;)

e.g. update-dep-const.js 
references on **@nrwl/nx/enforce-module-boundaries** switched to **@nx/enforce-module-boundaries.**

at least for me I was able to generate my domain.

**Comment by jatleti** [comment]
Any update about the new versión with angular 16? thanks!

**Comment by michael-zerna** [comment]
Any updates on this?
