### ISSUE TITLE
create domain command create files outside libs and inside libs

### ISSUE THREAD

**Issue by jon9090** [angular-architects/nx-ddd-plugin#143]
ddd is create a domain outside libs and inside the libs.

<img width="928" alt="image" src="https://github.com/angular-architects/nx-ddd-plugin/assets/74149517/6611770d-594d-42e3-a9b9-2beb91ea1cd6">

**Comment by oinfantedev** [comment]
Hi, I have the same problem when I create a domain it is generated outside of libs and inside of libs

![image](https://github.com/angular-architects/nx-ddd-plugin/assets/150563230/e3d4565a-a0f0-4443-91d2-a240a8f6b336)

**Comment by st-clair-clarke** [comment]
Same problem as above too.

**Comment by st-clair-clarke** [comment]
Same issue here too!

**Comment by manfredsteyer** [comment]
this is now solved with version 19.

Before version 19, just make sure you have an app and a lib folder before running this command.
