### ISSUE TITLE
[Help] Schematics other than domain / feature

### ISSUE THREAD

**Issue by dtodt** [angular-architects/nx-ddd-plugin#27]
Hi, I'm new to this plugin, so I was learning how do to things.

I've found in `nx-ddd-plugin/libs/ddd/collection.json`, these types: `domain`, `feature`, `ui` and `util`.
And in this issue, https://github.com/angular-architects/nx-ddd-plugin/issues/15#issuecomment-660503910, something like this:
```
ng g [...]:domain
ng g [...]:feature
ng g [...]:util
ng g [...]:ui
ng g [...]:api
```

But when I try this command: `ng g @angular-architects/ddd:ui todo`

It gives me this error:
```shell
$ nx g @angular-architects/ddd:ui todo
An unhandled exception occurred: Schematic "ui" not found in collection "@angular-architects/ddd".
See "/private/var/folders/5q/vp21tsm932z9chmrch5ch6tc0000gn/T/ng-91UPZX/angular-errors.log" for further details.
error Command failed with exit code 127.
```

Os: MacOs Catalina
Node: v14.14.0
Yarn: 1.22.10
Angular: v9
Nx: v9

I want to speed up my workspace development with this plugin, so, any help will be appreciated.

Thanks.

**Comment by pascalbe-dev** [comment]
Hi @dtodt 
you are right. The UI and util libs have been implemented. However, they are not released yet. I guess, we need to wait the next release.

**Comment by pascalbe-dev** [comment]
This is released now 👍 
See here: https://github.com/angular-architects/nx-ddd-plugin/releases/tag/1.1.0

This also brings different features like an ngrx flag for domain libs 🔥

**Comment by Frikki** [comment]
@manfredsteyer I guess this issue could be closed now.

**Comment by manfredsteyer** [comment]
+1 Thanks. Meanwhile we have such generators.
