### ISSUE TITLE
[Question] Why is generating an app for ngrx flag mandatory

### ISSUE THREAD

**Issue by JonasStn** [angular-architects/nx-ddd-plugin#32]
I don't understand why we are forced to generate an app when we just want to generate a domain using ngrx flag. Could the plugin not just skip adding the root store part in an app.

Also the current documentation is unclear because these commands:

```
ng g @angular-architects/ddd:domain booking --addApp --ngrx
ng g @angular-architects/ddd:feature search --domain booking --entity flight --ngrx
[...]
```

Do not result in the dependency graph as shown. 

My current workaround is to generate a domain and clean up afterwards, could this be changed in the future?

**Comment by pascalbe-dev** [comment]
I agree. Not everyone has an app for each domain. It's probably often the case, that you want one app which pulls in features from different domains. 

@manfredsteyer @peterbsmith2 
what do you think?

**Comment by manfredsteyer** [comment]
Good point. Honestly, I don't remember the reason.
@peterbsmyth - Do you remember it?

**Comment by manfredsteyer** [comment]
In version 2.0.0 this will be optional
