### ISSUE TITLE
[Feature Request] Optionally add tags

### ISSUE THREAD

**Issue by benpsnyder** [angular-architects/nx-ddd-plugin#38]
I want to add custom tags, like `--tags=platform:desktop` or `--tags=platform:web` or `--tags=platform:mobile` when generating a `Feature`

**Comment by bilaljaved9215** [comment]
@benpsnyder me working on this...

**Comment by benpsnyder** [comment]
Thanks @bilaljaved9215 - as discussed today, considering the use case where we have the following apps defined, with deployment targets of **desktop**, **web** and **mobile** (using nxtend or xplat community plugins)
![image](https://user-images.githubusercontent.com/707567/103735345-de2e7f80-4fbb-11eb-89c1-9b20e7ff7ce9.png)

And shells within the domains where features will be aggregated
![image](https://user-images.githubusercontent.com/707567/103735285-b7704900-4fbb-11eb-8691-e8ad4a492e23.png)

Please make it so we can tag Feature modules by platform and where eslint enforcement rules are defined for each Domain for platforms

**Comment by peterbsmith2** [comment]
seems cool. i agree that having a consideration of platforms is valuable.

**Comment by peterbsmyth** [comment]
![DDD extended with platforms](https://user-images.githubusercontent.com/76528868/104458080-e157db80-5578-11eb-9f89-d80d8758445c.png)

**Comment by peterbsmith2** [comment]
i think the solution is to add a "tags" input like the @nrwl/angular:application schematic as well as a "directory" input like @nrwl/angular:library

**Comment by manfredsteyer** [comment]
@benpsnyder Care for a PR that allows using --tags?
