### ISSUE TITLE
Request - Use eslint instead of tslint

### ISSUE THREAD

**Issue by st-clair-clarke** [angular-architects/nx-ddd-plugin#39]
Hi, I like what the plugin does. However, tslint IS deprecated, which prevents me from using the package. Angular 11 flags tslint as deprecated too. Is there a timeline to switch to eslint?

Thanks

**Comment by manfredsteyer** [comment]
Hi,

the good news are: The library is already supporting eslint. If it detects an `.eslintrc` file it assumes it should create its rules there.

Does this work for you?

Best wishes,
Manfred

**Comment by st-clair-clarke** [comment]
Your suggestion above does not work. I have tried both .eslintrc and eslintrc.js, yet the linting is created with tslint. I have even generated a new project and remove all tslint references yeat the schematics installs tslint and use it as the default. Please take a look at the schematics for me. 

If I use the deprecated package, it might prove very time consuming to remove it later.
