### ISSUE TITLE
feature naming convention

### ISSUE THREAD

**Issue by bhupatikrish** [angular-architects/nx-ddd-plugin#4]
Manfres, This is a great plugin for nx tooling. Thank you for creating this.

Can you please generate the 'feature' with angular style guide convention. i,e please keep the type to the end. i.e name.type.exn 
Example: instead of "feature-search" name it "search-feature" so it's consistent with other artifacts.
https://angular.io/guide/styleguide#general-naming-guidelines.

**Comment by manfredsteyer** [comment]
Thanks for this feedback.

We are doing this on purpose to see all libs of the same time side by side when sorting. It also aligns with the ideas of Nx.
