### ISSUE TITLE
[Bug] Add support for workspace.json instead of just angular.json

### ISSUE THREAD

**Issue by benpsnyder** [angular-architects/nx-ddd-plugin#40]
When running schematics and when I have `workspace.json` and not `angular.json`, I have to temporarily rename `mv workspace.json angular.json`

**Comment by benpsnyder** [comment]
Reference how they handle here: https://github.com/nrwl/nx/blob/master/packages/cli/lib/find-workspace-root.ts

**Comment by manfredsteyer** [comment]
I'm wondering: What is the reason for using a workspace.json instead of an angular.json in an Angular project?

**Comment by manfredsteyer** [comment]
Oh, also, seems like we don't use neither angular.json nor workspace.json in our code. Do I miss sth?

**Comment by manfredsteyer** [comment]
The next version (2.0.0) is based on Nx Generators and the associated helper functions, e. g. for working with config files. Hence, this will work.
