### ISSUE TITLE
[Bug] Support .eslintrc.json as well as .eslintrc

### ISSUE THREAD

**Issue by benpsnyder** [angular-architects/nx-ddd-plugin#41]
Hi,

the good news are: The library is already supporting eslint. If it detects an `.eslintrc` file it assumes it should create its rules there.

Does this work for you?

Best wishes,
Manfred

_Originally posted by @manfredsteyer in https://github.com/angular-architects/nx-ddd-plugin/issues/39#issuecomment-754229659_

**Comment by benpsnyder** [comment]
Please update to detect .eslintrc.json as well as .eslintrc

**Comment by manfredsteyer** [comment]
Forgot to close this one. .eslintrc is a first-class citizen meanwhile
