### ISSUE TITLE
[Bug] Fix import paths with '/' so that libraries could be published to a registry

### ISSUE THREAD

**Issue by smarletta** [angular-architects/nx-ddd-plugin#47]
Hi,

we are currently struggling when we want to publish our libraries to make them accessible for other teams. On a look on the generated import paths we saw:

@scope/moduleName/feature

I guess for being publishable it should be:

@scope/moduleName-featureName

Or did we misunderstand the approach?

regards
sebastiano

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. The next version of this plugin allows you to do the following:

--type=publishable --importPath a-b-c

The importPath is the name, you want to use for npm.
