### ISSUE TITLE
nx console not showing @angular-architects/ddd when using webstorm.

### ISSUE THREAD

**Issue by soacs** [angular-architects/nx-ddd-plugin#49]
I noticed Peter gave a demo using vscode and saw the generate @angular-architects/ddd:domain, etc when using the nx console.

In webstorm 2020.3.2 when using the nx console, I do not see the @angular-architects:ddd options..... in the list of schemaitics.

Also what is the proper way to add @angular-architects:ddd using nx?

**Comment by wizardnet972** [comment]
try to install ddd schematics and reopen the webstorm

**Comment by Gorethrone** [comment]
Hi soacs, I ran into the same problem and I am a little shocked that no one could help you until now. Maybe you got it working yourself by now if not here are the steps to get it working in WebStorm:

1. Install nx-webstorm plugin for WebStorm (https://plugins.jetbrains.com/plugin/15000-nx-webstorm)
2. Create a new Nx-Workspace with `npx create-nx-workspace@latest`
3. Add the angular-architects/ddd plugin to the workspace with `ng add @angular-architects/ddd`
4. Then go to settings in WebStorm (CTRL+ALT+S) -> Tools -> Nx Plugin Settings -> External Schematics
5. Here you add the angular-architects/ddd package `@angular-architects/ddd`
6. And finish! Now you can choose the new schematics from the Nx plugin (maybe you need to invalidate cache and restart)

I hope this was of any help for you or for anyone else having this problem.

Have a nice day :)
