### ISSUE TITLE
[Question] Why is a feature not allowed to import another feature

### ISSUE THREAD

**Issue by ngfelixl** [angular-architects/nx-ddd-plugin#50]
Hi,

thank you for developing this great library and providing the related knowledge. While working with NX DDD, it turned out that I am struggling with the imports of a feature into another feature. There is a "shell" feature of a domain with all its routing. In the routing I want to specify a component from a feature within the same domain. This however is not allowed, because in the root *.eslint.rc* it says

```json
{
  "sourceTag": "type:feature",
  "onlyDependOnLibsWithTags": [
    "type:ui",
    "type:domain-logic",
    "type:util"
  ]
}
```

When I was reading through Nrwls "Enterprise Angular Monorepo Patterns" eBook, I found out that this type of restriction is not given here. Is this intended on your side or is the "type:feature" missing in the list of **onlyDependOnLibsWithTags**? If so, I would be happy to support and submit a PR.

Thank you in advance!

**Comment by manfredsteyer** [comment]
We don't generate rules for this by default, b/c it might produce cycles.
