### ISSUE TITLE
[Question] Which approach should I use to create a ui-module (dumb components)? 

### ISSUE THREAD

**Issue by wizardnet972** [angular-architects/nx-ddd-plugin#52]
Which approach is better to create a ui-module (dumb components)? 

Create ui-module-s per `feature-` 
```
auth:
 feature-login
 ui-login-form

 feature-register
 ui-register-form

 shared
   social-links

```
**OR**
create one ui-module (`ui-auth`) and inside all create all components for all features?
```
auth:
  feature-login
  feature-register
  ui-auth:
    lib/src/components/login-form
    lib/src/components/register-form
    lib/src/components/social-links
```

**Comment by manfredsteyer** [comment]
Perhaps, it's best to start with one lib. If the lib grows to big, you can split it into several. E. g. if it has (far) more than 7+/- components.
