### ISSUE TITLE
missing type:api

### ISSUE THREAD

**Issue by wizardnet972** [angular-architects/nx-ddd-plugin#53]
In the source code missing schematics for adding api library with `type:api` tag.

Sometimes developers can forget to add this tag every time they create `@nrwl/node:lib` so I think it should be option to create such a library.

**Comment by manfredsteyer** [comment]
Yes, good point. Care for a PR?

**Comment by wizardnet972** [comment]
Yes. I'll send soon :)

**Comment by manfredsteyer** [comment]
The next version (2.0.0) will have such a generator.
