### ISSUE TITLE
Can `type:api` depend on another `type:api`?

### ISSUE THREAD

**Issue by wizardnet972** [angular-architects/nx-ddd-plugin#54]
Can `type:api` depend on another `type:api`?

Consider the case when you have api-lib deepened on another api-lib

```
{
  "sourceTag": "type:api",
  "onlyDependOnLibsWithTags": [
    "type:ui",
    "type:domain-logic",
    "type:util"
  ]
},
```

**Comment by manfredsteyer** [comment]
We don't generate rules for this by default, b/c it might produce cycles.
