### ISSUE TITLE
Why type:ui can't depends on another type:ui?

### ISSUE THREAD

**Issue by wizardnet972** [angular-architects/nx-ddd-plugin#56]
I create a shared ui library (`libs/shared/ui/ui-common`) and I want to use it inside domain/ui-xxx but I got an error:

`A project tagged with "type:ui" can only depend on libs tagged with "type:domain-logic", "type:util"`

The UI inside domain-lib can't depend on shared?

**Comment by manfredsteyer** [comment]
We don't generate rules for this by default, b/c it might produce cycles.
