### ISSUE TITLE
[Question] How to import ui component without breaking ddd rules?

### ISSUE THREAD

**Issue by wizardnet972** [angular-architects/nx-ddd-plugin#57]
How to import ui component without breaking ddd rules?

I have `libs/reports/ui-grid` and I want to import it in `libs/dashboard/feature-shell`.

This library contains a list of cards display list of reports details (the data come from report service inside the domain).

--

How should I do it without breaking the ddd rules?

1. Export the component from `ui-grid` and import it in `dashabord/feature-shell`?
2. Create inside `libs/shared` and import the shared in `dashabord/feature-shell` and get the data from `libs/report/api`?
3. export the component in `libs/report/api` and import it in `dashabord/feature-shell`?

**Comment by manfredsteyer** [comment]
Both is fine. Just beware of having a shared folder that grows too big.
