### ISSUE TITLE
[Question] What could an API look like?

### ISSUE THREAD

**Issue by PhilippFreibauer** [angular-architects/nx-ddd-plugin#70]
Assuming I have two domains, a product and an order, the order requires data from the product and then has to access the corresponding domain via an API. What could an API look like here? Is the product data service for the other domain simply exported in a module?

**Comment by manfredsteyer** [comment]
Hi Philipp,

it's basically a lib with just an index.ts exporting other stuff from the domain.

**Comment by wizardnet972** [comment]
@PhilippFreibauer You can also expose tokens to configure stuff from the domain.

**Comment by jon9090** [comment]
@manfredsteyer it can be exporting also feature modules? to use in another libs?

**Comment by manfredsteyer** [comment]
In theory, yes. However, if you allow an API to export features, you can end up with cycles. Hence, I really try hard to prevent the need for this.
