### ISSUE TITLE
Angular 12 / Nx 12.3 - ui-options" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID

### ISSUE THREAD

**Issue by bjornharvold** [angular-architects/nx-ddd-plugin#74]
Got this error when trying to create a new library for the first time after migrating to Angular 12

Command:
`npx nx g @angular-architects/ddd:ui qr-code --domain shared`

Warning:
`ui-options" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID`

**Comment by manfredsteyer** [comment]
Thanks for pointing this out. We will resolve this with the next release.

**Comment by manfredsteyer** [comment]
It's done with version 1.4
