### ISSUE TITLE
Error: Cannot find configuration for _library-name_ in /angular.json (Nx 12.4)

### ISSUE THREAD

**Issue by manfredsteyer** [angular-architects/nx-ddd-plugin#81]
This error occurs when the plugin tries to create a library, e. g. a domain library.

This is related to the following issues in Nx 12.4:
https://github.com/nrwl/nx/issues/6065

A temp. solution is downgrading to Nx 12.3.x

**Comment by wizardnet972** [comment]
@manfredsteyer can you publish a new version for the last pr, please?

**Comment by iameduardod** [comment]
how do you downgrade to nx 12.3.x ? simply just running `npx create-nx-workspace@12.3.6` ? @manfredsteyer

**Comment by wizardnet972** [comment]
The problem fixed nx 12.5.1

**Comment by manfredsteyer** [comment]
Thanks for this good message, @wizardnet972. It's always cool if issues resolve themselves.
