### ISSUE TITLE
feature request: add SCAM support 

### ISSUE THREAD

**Issue by wizardnet972** [angular-architects/nx-ddd-plugin#82]
Add an option to create components as Single Angular Module Schematics using the schematics.

Single Angular Module Schematics makes tree-shaking much better.

The file should have both decorators: `@Component` and `@NgModule`.

```
@Component(...)
export class Component... 

@NgModule({
  declarations: [Component...],
  exports: [Component]
})
export class Module...
```

@manfredsteyer I can send PR quickly.

**Comment by wizardnet972** [comment]
in a second thought, the `ddd `doesn't create ui components.

**Comment by manfredsteyer** [comment]
I really like the SCAM idea as a mental model. For the implementation, I'd rather wait for Standalone Components
