### ISSUE TITLE
Feature Request - Way to Easily Extend Schematics

### ISSUE THREAD

**Issue by tuckerjt07** [angular-architects/nx-ddd-plugin#84]
I'm not even sure if this is possible/feasible but I am looking for a way to add custom build options when creating a new domain, namely stylePreprocessorOptions and extractCss so that my shared styles are automatically included in the new domain. Based on my limited understanding and research it looks like extending the existing schematic is the best way to accomplish this but I am running into an issue tracking down exactly what needs to be extended.

Another nice to have would be being able to add code when generating a feature. In this case just adding '@use variables;' to the features scss file to pull in access to all the shared styles.

**Comment by manfredsteyer** [comment]
I feel you.

I think, the easiest way is to create a workspace generator (version 2.0.0 will use the generator API) and wrap it:

```typescript
import { Tree } from '@nrwl/devkit';
import generateFeature from '@angular-architects/ddd/src/generators/feature';

export default async function (tree: Tree, schema: any) {
  
  generateFeature(tree, { name:'my-feature', domain: 'my-domain' });

  // Do additional stuff with generated feature
  
}
```
