### ISSUE TITLE
lint doesn't allow me to import from type:api in the feature or domain of another lib-domain

### ISSUE THREAD

**Issue by jon9090** [angular-architects/nx-ddd-plugin#93]
@manfredsteyer  According to your article about ddd, it describe that feature can import something from api of another feature.
(The arrow in the picture)

But the ddd plugin lint doesn't allow me to make that import. 

http://www1.angulararchitects.io.dedi1415.your-server.de/aktuelles/tactical-domain-driven-design-with-monorepos/

![image](https://user-images.githubusercontent.com/74149517/144715807-da12eaa5-c98e-41c8-be40-d1a859495974.png)

**Comment by manfredsteyer** [comment]
Yes, that's right. For this, you needed to add some tags and rules by hand.
