### ISSUE TITLE
Not compatible with "@nrwl/angular" > 13.3.6

### ISSUE THREAD

**Issue by dc-p8** [angular-architects/nx-ddd-plugin#95]
The @nrwl/angular library generator removed the 'style' argument in this commit : https://github.com/nrwl/nx/commit/2b00c99db1ea5db93f99997c9d1ab9cebe7a1783#diff-541dd49c7729700f4e63f4d0f04435e17d9d6a80359ea38796405f32b38ed5af

Now when I try to use ddd, which still send 'style' argument, I receive this error :

```
$ node node_modules/@nrwl/cli/bin/nx.js generate @angular-architects/ddd:domain --name=dummy --type=buildable --no-interactive --dry-run


InvalidInputOptions [Error]: Schematic input does not validate against the Schema: {"name":"domain","directory":"dummy","tags":"domain:dummy,type:domain-logic","style":"scss","prefix":"dummy","publishable":false,"buildable":true}
errors: [
    {
      instancePath: '',
      schemaPath: '#/additionalProperties',
      keyword: 'additionalProperties',
      params: [Object],
      message: 'must NOT have additional properties'
    }
  ]
}

  Data path "" must NOT have additional properties(style).
```

Downgrading @nrwl/angular to 13.3.6 solved the issue.

**Comment by sergidt** [comment]
I have the same problem, is not compatible, I got the same error!!!!

**Comment by manfredsteyer** [comment]
+1 A new version will arrive soon.
